app/src/main/java/io/intrepid/contest/base/BaseActivity.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImageActivity.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryname/EntryNameActivity.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/join/JoinActivity.java

Another tiny PR just to add back button in the action bar.
Even though I have set up the behavior of the button in the `BaseActivity`, I have not enabled it by default in the views, because some screens don't have it or have a different button (e.g. a cross to close).
Also the behavior I set up is the same as pressing the back button, because I imagine that the `EntryNameActivity` can be started both after Joining a contest and after Reopening a contest you have already joined.

Add back button to activities

---

app/build.gradle
app/src/androidTest/java/io/intrepid/contest/InstrumentationTestApplication.java
app/src/androidTest/java/io/intrepid/contest/rest/TestRestClient.java
app/src/main/AndroidManifest.xml
app/src/main/java/io/intrepid/contest/ContestApplication.java
app/src/main/java/io/intrepid/contest/base/BasePresenter.java
app/src/main/java/io/intrepid/contest/base/PresenterConfiguration.java
app/src/main/java/io/intrepid/contest/customviews/HintLabelEditText.java
app/src/main/java/io/intrepid/contest/models/InvitationResponse.java
app/src/main/java/io/intrepid/contest/rest/RestApi.java
app/src/main/java/io/intrepid/contest/rest/RetrofitClient.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/namecontest/NameContestFragment.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImageActivity.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImageContract.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/join/JoinActivity.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/join/JoinContract.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/join/JoinPresenter.java
app/src/main/java/io/intrepid/contest/screens/splash/SplashPresenter.java
app/src/main/java/io/intrepid/contest/settings/SharedPreferencesManager.java
app/src/main/java/io/intrepid/contest/settings/UserSettings.java
app/src/main/java/io/intrepid/contest/utils/RxUtils.java
app/src/main/res/values/strings.xml
app/src/test/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImagePresenterTest.java
app/src/test/java/io/intrepid/contest/screens/entrysubmission/join/JoinPresenterTest.java
app/src/test/java/io/intrepid/contest/testutils/BasePresenterTest.java
app/src/test/java/io/intrepid/contest/testutils/TestPresenterConfiguration.java
app/src/test/java/io/intrepid/contest/utils/RxUtilsTest.java

This PR touches many files from the Skeleton, but I haven't come up with any new code myself: I copied it all either from [Skeleton](https://github.com/IntrepidPursuits/AndroidSkeleton) itself, or from [Northeastern](https://github.com/IntrepidPursuits/northeastern-isle-android) (which also uses some version of Skeleton)
- The API endpoint I'm using is not live yet, so I receive a 404 error when it's called. For that I added a [toast](https://github.com/IntrepidPursuits/ContestAndroid/compare/master...gabi/mock-api#diff-9420d6573f9d9b3821adfe82b919922bR89) that, in debug mode, also takes the user to the next screen so we're not stuck there.
- I am not using [`TestConfig`](https://github.com/IntrepidPursuits/ContestAndroid/blob/gabi/mock-api/app/src/main/java/io/intrepid/contest/TestConfig. …

Add API call to join contest with code

---

app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusActivity.java
app/src/main/res/layout/activity_contest_status.xml
app/src/main/res/layout/activity_fragment_container.xml

https://intrepid.atlassian.net/browse/CON-147
Copying from the skeleton I didn't realize other screens were using the same layout.
Only the ContestStatus layout should have the skip button (and only for now).
Later this button will be removed.

CON-147 Create separate layout for Contest Status activity

---

app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestActivity.java

Small bug fix related to navigating back without actually entering a new category.
The bug can currently be reproduced by clicking the Add Category fab button and then hitting the back key button on the Android device.

bug fix init

---

app/src/main/java/io/intrepid/contest/ContestApplication.java
app/src/main/java/io/intrepid/contest/rest/ContestStatusResponse.java
app/src/main/java/io/intrepid/contest/rest/MockRestApi.java
app/src/main/java/io/intrepid/contest/rest/RestApi.java
app/src/main/java/io/intrepid/contest/rest/RetrofitClient.java
app/src/main/java/io/intrepid/contest/rest/UserCreationResponse.java
app/src/main/java/io/intrepid/contest/screens/contestoverview/ContestOverviewActivity.java
app/src/main/java/io/intrepid/contest/screens/contestoverview/ContestOverviewContract.java
app/src/main/java/io/intrepid/contest/screens/contestoverview/ContestOverviewPresenter.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusActivity.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusContract.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenter.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/resultsavailable/ResultsAvailablePresenter.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/waitingsubmissions/WaitingSubmissionsPresenter.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImagePresenter.java
app/src/main/java/io/intrepid/contest/screens/join/JoinPresenter.java
app/src/main/res/layout/activity_contest_status.xml
app/src/test/java/io/intrepid/contest/screens/contestoverview/ContestOverviewPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/join/JoinPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/splash/SplashPresenterTest.java

https://intrepid.atlassian.net/browse/CON-149
PART 2
Please look only at last commit: https://github.com/IntrepidPursuits/ContestAndroid/pull/39/commits/f046a8ff82e7f32443e49cd2e2f6b08996b7e596
- Update API endpoint according to web team's changes (PR waiting for approval)
- Update logic to handle that change, and also come back with logic to display `ContestOverview` for judges (that was hardcoded in the OK button, and the logic was not updated to do the same after the timer runs, so it was never displayed)
- Undo misunderstanding about data in `ContestOverviewActivity`. I had understood that the number displayed in the screen (https://zpl.io/HLz5o) was submissions waiting to be sent by contestants. Obviously that was a mistake, the number is actually submissions waiting to be scored by …

CON-149: Refactor API mocks

---

app/src/main/java/io/intrepid/contest/screens/contestcreation/ContestCreationFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestActivity.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/addcategoriestocontest/AddCategoriesFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/describecontest/DescribeContestFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/namecontest/NameContestFragment.java
app/src/main/java/io/intrepid/contest/utils/SlidingTabAdapter.java

This bug occurs when you re-navigate to a tabbed fragment  that now has some text in it, and thus should display the next arrow.
EX: Go forward a few times, then go backwards to Name Contest…and then forward again to Describe Contest Page

Add OnPageChangeListener - Fix nav flow error

---

app/src/main/java/io/intrepid/contest/rest/RetrofitClient.java

Policy was wrong, so pojos were not getting assigned their variables.

Fix gson field naming policy to match the API

---

app/src/main/java/io/intrepid/contest/rest/ContestStatus.java
app/src/main/java/io/intrepid/contest/rest/ContestStatusResponse.java
app/src/main/java/io/intrepid/contest/rest/MockRestApi.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenter.java
app/src/test/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenterTest.java

Before, the `ContestStatusResponse` pojo had the variables directly. However there is a "contest_status" key wrapping that, so code was changed to account for that.

Update contest status pojo according to api endpoint

---

app/src/main/java/io/intrepid/contest/screens/contestcreation/ContestCreationFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/ValidatableView.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/describecontest/DescribeContestContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/describecontest/DescribeContestFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/describecontest/DescribeContestPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/editcategoriestocontest/EditCategoriesFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/namecontest/NameContestFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/reviewcontest/ReviewContestFragment.java
app/src/test/java/io/intrepid/contest/screens/contestcreation/describecontest/DescribeContestPresenterTest.java

In contest creation flow, optional fields should allow going to the next screen.
Removed onFocus method from ContesCreationFragment interface, since the only classes that were previously using it were NameContestFragment and DescribeContestFragment.
The onFocus method has now been moved to ValidatableVIew interface.
The DescribeContestPresenter's interface has thus been simpliied. Same for the DescribeContestPresenter test suite.

CON-172 - Fixed Contest Creation Navigation Flow

---

app/src/main/java/io/intrepid/contest/rest/EntryRequest.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImagePresenter.java
app/src/main/java/io/intrepid/contest/utils/ImageUtils.java

https://intrepid.atlassian.net/browse/CON-196
- API endpoint needed to receive a prefix.
- Presenter was not deciding the format/quality of the picture
IMPORTANT:
How to test:
1. Uninstall the app
2. Install it again (so you have a fresh)
3. If you are not using the QA build to install it, go 
4. Join a contest
5. Enter **one** of the following codes:
- 1adSkR3
- wvCVymv
- frkgUx8
(If they're all used up, please see steps 9-10)
6. Create an entry
7. Select an image
8. Click submit and **wait** (there's no progress bar, so it takes a few seconds)
You should see a successful message. If it says it's waiting on 0 contestants it's because no one else that was invited redeemed the code, and the submissions have not been ended automatically or manually.
9. If needed: With postman, send an …

CON-196: Fix API endpoint to submit entry image

---

app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsActivity.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsActivityContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsPresenter.java
app/src/test/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsPresenterTest.java

https://intrepid.atlassian.net/browse/CON-197
- Cannot go back to contest creation when seeing "preview content" (intro message or selected contacts)
- Should go back to "preview content" if currently selecting contacts

CON-197: Back button behavior in send invitations screen

---

app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListPresenter.java
app/src/test/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListPresenterTest.java

Categories List should hide next screen when all categories have been removed.
It should reappear when the categories list is no longer empty.
Still figuring out with design how to handle the empty screen that results from emptying all the categories.

Con 200 - Categories List should hide next screen

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/intrepid/contest/models/ContestResult.java
app/src/main/java/io/intrepid/contest/models/RankedEntryResult.java
app/src/main/java/io/intrepid/contest/rest/ContestResultResponse.java
app/src/main/java/io/intrepid/contest/rest/MockRestApi.java
app/src/main/java/io/intrepid/contest/rest/RestApi.java
app/src/main/java/io/intrepid/contest/screens/contestresults/ContestResultsActivity.java
app/src/main/java/io/intrepid/contest/screens/contestresults/ContestResultsAdapter.java
app/src/main/java/io/intrepid/contest/screens/contestresults/ContestResultsContract.java
app/src/main/java/io/intrepid/contest/screens/contestresults/ContestResultsPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestresults/ContestResultsViewHolder.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/resultsavailable/ResultsAvailableFragment.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/resultsavailable/ResultsAvailablePresenter.java
app/src/main/res/layout/activity_contest_results.xml
app/src/main/res/layout/contest_result_row_item.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/intrepid/contest/screens/contestresults/ContestResultsPresenterTest.java

https://intrepid.atlassian.net/browse/CON-211
- Includes hooking it up to contest status: https://intrepid.atlassian.net/browse/CON-213
- Does not include displaying the score details: https://intrepid.atlassian.net/browse/CON-212
I did add some unused fields in my pojos, but I just wanted to make sure they were being retrieved from the API. They will be used in the next subtask (CON-212). I can remove them if you think it's a bad idea to have them merged in now.

CON-211: Results screen

---

app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsActivity.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsPresenter.java
app/src/test/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsPresenterTest.java

https://intrepid.atlassian.net/browse/CON-217
- Skip inviting contestants now updates app bar title (`onCreateOptionsMenu()` was never called after refectoring of activity)
- Also changes the name of the variable `participationType` because that raised confusion about whether it was changing the participationType of the current user, or indicating which type of user was being invited in the screen

CON-217: Skip inviting contestants update app bar title

---

app/src/main/java/io/intrepid/contest/base/BaseActivity.java
app/src/main/java/io/intrepid/contest/rest/MockRestApi.java
app/src/main/java/io/intrepid/contest/rest/RestApi.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestPresenter.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenter.java
app/src/test/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenterTest.java

When contest has already ended, screen for judges should show contest status rather than an overview.
This was initially tested with Postman, by creating a user in postman, creating a contest, inviting a judge and thenjoining the app as a judge before ending the contest in postman.
Changing the order of this does not ensure the same results though:  Ending the contest before attempting to join as a judge with the code appears to be registered by the api as a regular contestant code instead.

Support contest status for judge flow

---

app/src/main/java/io/intrepid/contest/screens/contestjudging/scoreentries/entrieslist/EntriesListFragment.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusActivity.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenter.java
app/src/test/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenterTest.java

Judge Flow should show wait screen or results depending on contest status
* API does not support identifying the judges participating in this contest. This uses an intent extra instead to indicate whether or not judge participant just submitted a score. This is one approach for determining if the current user just submitted scores given that we cannot query the api for this information.

Con 233 - After judging, show Wait Screen or Results

---

app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImagePresenter.java
app/src/test/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImagePresenterTest.java

Entry submission always expected a `croppedUri`, breaking when the user selected "No, thanks" to sending an image.

Fix entry submission without an image

---

app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImageActivity.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImageContract.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImagePresenter.java
app/src/main/res/layout/activity_entry_image.xml
app/src/main/res/layout/entry_image_choose_layout.xml
app/src/main/res/layout/entry_image_preview_layout.xml
app/src/test/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImagePresenterTest.java

- Instead of showing/hiding layout in the main layout xml, transition between 2 scenes (each one created form a layout)
- Advantage of this approach:
- Cleaner code
- Easy animation effect
- Disadvantages:
- Layout elements have to be inflated every time there is a transition (but it's not expected that this will happen many times)
- The Butterknife binding is not straightforward with elements being inflated in the layout later. [The first commit](https://github.com/IntrepidPursuits/ContestAndroid/commit/048ddc71b99feb88c04da63300529e3364164b11) has one approach (binding happens in the activity's code), and [the second](https://github.com/IntrepidPursuits/ContestAndroid/commit/38480a55c469ea99aa12a55c6de82d4a8aa2df77) has another (binding happens in another class, as [suggested by Jake …

Use Transition Framework Scenes in EntryImageActivity

---

app/src/main/java/io/intrepid/contest/screens/splash/SplashPresenter.java
app/src/test/java/io/intrepid/contest/screens/splash/SplashPresenterTest.java

https://intrepid.atlassian.net/browse/CON-239
Currently the API returns `participationType` as `null` if the user was a creator of the contest.

CON-239: Fix accessing previous contest as creator

---

app/src/main/java/io/intrepid/contest/screens/join/JoinPresenter.java
app/src/test/java/io/intrepid/contest/screens/join/JoinPresenterTest.java

https://intrepid.atlassian.net/browse/CON-179
Duplicate: https://intrepid.atlassian.net/browse/CON-166
Error message only appeared for mock api. Now it appears when using the real API (by checking http error code == 404).

CON-179: Error message when joining with incorrect code

---

app/src/main/java/io/intrepid/contest/models/Contest.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/ContestCreationFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoryAdapter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoryClickListener.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/describecontest/DescribeContestContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/describecontest/DescribeContestFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/editcategoriestocontest/EditCategoriesContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/editcategoriestocontest/EditCategoriesFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/reviewcontest/ReviewContestContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/reviewcontest/ReviewContestFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/reviewcontest/ReviewContestPresenter.java
app/src/test/java/io/intrepid/contest/screens/contestcreation/NewContestPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/contestcreation/reviewcontest/ReviewContestPresenterTest.java

https://intrepid.atlassian.net/browse/CON-242
When creating a contest, reordering categories had no effect. Now it is reflected in the categories list screen, and also in the review screen.
I propagated the [`onPageSelected` event to all fragments that belong to the viewpager](https://github.com/IntrepidPursuits/ContestAndroid/compare/master...gabi/242-category-order#diff-1281f68e978e70e739f42217e991356fR21), because I felt weird about creating an interface just for the [one fragment that is using it now](https://github.com/IntrepidPursuits/ContestAndroid/compare/master...gabi/242-category-order#diff-225cdb076d0568c9c2cbb117f5488726R88), and I thought it would be weird for the presenter to check for that specific fragment in the [`NewContestPresenter`](https://github.com/IntrepidPursuits/C …

CON-242: Apply category reordering

---

app/src/main/java/io/intrepid/contest/base/BaseActivity.kt
app/src/main/java/io/intrepid/contest/base/BaseFragmentActivity.kt
app/src/main/java/io/intrepid/contest/base/BaseMvpActivity.kt
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/ValidatableContestCreationFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/namecontest/NameContestFragment.java
app/src/test/java/io/intrepid/contest/screens/contestcreation/NewContestPresenterTest.kt
app/src/test/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListPresenterTest.kt

[ 🎉 Friday Time! 🎈 ]
https://intrepid.atlassian.net/browse/CON-245
- Crash on canceling category creation was caused by `onActivityResult()` not allowing null parameters. Base classes have been updated according to skotlinton to allow nonnull parameters.
- Crash on submitting category was caused by `lateinit presenter` not being initialized before use (use being checking for null). There's still one comparison of `getPresenter() != null` in another class but that will be solved in another PR.

245: Fix crash on creating categories
