IntrepidPursuits/ContestAndroid

app/src/main/AndroidManifest.xml
app/src/main/java/io/intrepid/contest/screens/entrysubmission/join/JoinActivity.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/join/JoinContract.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/join/JoinPresenter.java
app/src/main/java/io/intrepid/contest/splash/SplashActivity.java
app/src/main/res/layout/activity_join.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImagePresenterTest.java
app/src/test/java/io/intrepid/contest/screens/entrysubmission/entryname/EntryNamePresenterTest.java
app/src/test/java/io/intrepid/contest/screens/entrysubmission/join/JoinPresenterTest.java

* Lacking look-and-feel
* Lacking connection to API
* Package: I created it in the package **entrysubmission** because that's the epic for the story. However it's not related to an entry, it's just a necessary step before an entry submission. Might be appropriate to change it if it becomes confusing.

Create screen to join contest with a code

---

app/build.gradle
app/src/main/java/io/intrepid/contest/base/BaseActivity.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImageActivity.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryname/EntryNameActivity.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/join/JoinActivity.java
app/src/main/res/drawable/camera_icon.xml
app/src/main/res/drawable/gallery_icon.xml
app/src/main/res/layout/activity_entry_image.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

This is a tiny PR with the style for the button icons, so that @abassawo can use it when he updates his look-and-feel.
It also includes some UI updates in my screens, including changing the appbar title. I am now always using `onViewCreated` instead of `onCreate` in the activities, otherwise it doesn't get triggered.

Updated look and feel

---

app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImageActivity.java
app/src/main/res/layout/activity_entry_image.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

https://intrepid.atlassian.net/browse/CON-135
- Fix "choose entry image" screen according to designs/QA review
- Talking to the designers another change was needed, to change button text when no image is chosen
This does not fix the design issues in the image preview screen, those were described in a new user story: https://intrepid.atlassian.net/browse/CON-136

CON-135 Fix entry image screen

---

app/src/main/java/io/intrepid/contest/customviews/ClearableEditText.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/describecontest/DescribeContestFragment.java
app/src/main/res/layout/fragment_edit_contest_description.xml
app/src/main/res/layout/fragment_edit_contest_name.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/styles.xml

refined description page

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/intrepid/contest/base/BaseActivity.java
app/src/main/java/io/intrepid/contest/base/BaseContract.java
app/src/main/java/io/intrepid/contest/base/BaseFragment.java
app/src/main/java/io/intrepid/contest/rest/ContestStatusResponse.java
app/src/main/java/io/intrepid/contest/rest/InvitationResponse.java
app/src/main/java/io/intrepid/contest/rest/RestApi.java
app/src/main/java/io/intrepid/contest/rest/RetrofitClient.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusActivity.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusContract.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenter.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/waitingsubmissions/WaitingSubmissionsContract.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/waitingsubmissions/WaitingSubmissionsFragment.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/waitingsubmissions/WaitingSubmissionsPresenter.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImageActivity.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImageContract.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImagePresenter.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/join/JoinActivity.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/join/JoinContract.java
app/src/main/java/io/intrepid/contest/screens/entrysubmission/join/JoinPresenter.java
app/src/main/res/layout/fragment_waiting_submissions.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/plurals.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/test/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/conteststatus/waitingsubmissions/WaitingSubmissionsPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImagePresenterTest.java
app/src/test/java/io/intrepid/contest/screens/entrysubmission/join/JoinPresenterTest.java

https://intrepid.atlassian.net/browse/CON-129
- Does not include timer
- Does not include icon

CON-129 waiting submissions

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/intrepid/contest/base/BaseFragment.java
app/src/main/java/io/intrepid/contest/models/Participant.java
app/src/main/java/io/intrepid/contest/models/ParticipationType.java
app/src/main/java/io/intrepid/contest/rest/InvitationResponse.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusActivity.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenter.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/resultsavailable/ResultsAvailableFragment.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/waitingsubmissions/WaitingSubmissionsContract.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/waitingsubmissions/WaitingSubmissionsFragment.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/waitingsubmissions/WaitingSubmissionsPresenter.java
app/src/main/java/io/intrepid/contest/screens/join/JoinActivity.java
app/src/main/java/io/intrepid/contest/screens/join/JoinContract.java
app/src/main/java/io/intrepid/contest/screens/join/JoinPresenter.java
app/src/main/java/io/intrepid/contest/screens/splash/SplashActivity.java
app/src/main/java/io/intrepid/contest/settings/PersistentSettings.java
app/src/main/java/io/intrepid/contest/settings/SharedPreferencesManager.java
app/src/main/res/layout/activity_join.xml
app/src/main/res/layout/fragment_waiting_submissions.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/conteststatus/waitingsubmissions/WaitingSubmissionsPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/join/JoinPresenterTest.java

https://intrepid.atlassian.net/browse/CON-138
Show waiting for submissions screen for judges.
[Please look only at last 2 commits,](https://github.com/IntrepidPursuits/ContestAndroid/pull/26/files/f4727e8ce0d352fe918f4bf294d471f45877669f..bed2633e7674c4c203371bd1b508803f89a71230) since the others are from PR #25 .

CON-138 Judges "waiting for submissions" screen

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/intrepid/contest/base/BasePresenter.java
app/src/main/java/io/intrepid/contest/models/Category.java
app/src/main/java/io/intrepid/contest/models/Contest.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/EditContestContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestActivity.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestMvpContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/addcategoriestocontest/AddCategoriesFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/addcategoriestocontest/AddCategoriesPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/addcategoriestocontest/AddCategoryActivity.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/describecontest/DescribeContestFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/describecontest/DescribeContestPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/namecontest/NameContestContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/namecontest/NameContestFragment.java
app/src/main/java/io/intrepid/contest/utils/SlidingTabAdapter.java
app/src/main/res/layout/categories_list_fragment.xml
app/src/main/res/layout/fragment_edit_contest_category.xml
app/src/test/java/io/intrepid/contest/screens/contestcreation/NewContestPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/contestcreation/addcategoriestocontest/AddCategoriesPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListPresenterTest.java

As a contest creator, I want to add a scoring category to my contest, specifying name and range (stretch goal).

 CON-8 Abass/add category

---

app/src/main/res/values/strings.xml

https://intrepid.atlassian.net/browse/CON-145

CON-145 Fix text in contestant's waiting for submissions status screen

---

app/src/main/java/io/intrepid/contest/rest/RedeemInvitationRequest.java
app/src/main/java/io/intrepid/contest/rest/RedeemInvitationResponse.java
app/src/main/java/io/intrepid/contest/rest/RestApi.java
app/src/main/java/io/intrepid/contest/rest/RetrofitClient.java
app/src/main/java/io/intrepid/contest/screens/join/JoinPresenter.java
app/src/main/java/io/intrepid/contest/screens/splash/SplashPresenter.java
app/src/test/java/io/intrepid/contest/screens/join/JoinPresenterTest.java

https://intrepid.atlassian.net/browse/CON-146
1. Incorporated changes from the API:
- Authorization header changed
- Redeem code endpoint changed (now needs a body)
2. Clarified names of pojos

CON-146 Update API

---

app/src/main/java/io/intrepid/contest/models/User.java
app/src/main/java/io/intrepid/contest/rest/RestApi.java
app/src/main/java/io/intrepid/contest/rest/UserCreationRequest.java
app/src/main/java/io/intrepid/contest/screens/splash/SplashActivity.java
app/src/main/java/io/intrepid/contest/screens/splash/SplashContract.java
app/src/main/java/io/intrepid/contest/screens/splash/SplashPresenter.java
app/src/main/java/io/intrepid/contest/settings/PersistentSettings.java
app/src/main/java/io/intrepid/contest/settings/SharedPreferencesManager.java
app/src/main/res/layout/activity_splash.xml
app/src/test/java/io/intrepid/contest/screens/splash/SplashPresenterTest.java

https://intrepid.atlassian.net/browse/CON-101
[CLICK HERE TO REVIEW ONLY LAST 2 COMMITS.](https://github.com/IntrepidPursuits/ContestAndroid/pull/33/files/feea27d5ce1736f79edf6264881b12c440424bc0..020f5ee45194287729db9f71aca134e3abf0e606)
(It branches off of PR #31, `gabi/con-146-update-api`)

CON-101 Create user

---

app/src/main/java/io/intrepid/contest/screens/splash/SplashActivity.java
app/src/main/java/io/intrepid/contest/screens/splash/SplashPresenter.java
app/src/main/res/layout/activity_splash.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/styles.xml

https://intrepid.atlassian.net/browse/CON-151
This fixes the crashing problem in `master` (for some weird reason the layout attributes were not valid and it still built/run in the branch before it was merged into master).
The button cardview style is also consistent with `EntryImageActivity` now.
Authentication also works for users already created.

CON-151 Add missing layout attributes

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/intrepid/contest/screens/contestoverview/ContestOverviewActivity.java
app/src/main/java/io/intrepid/contest/screens/contestoverview/ContestOverviewContract.java
app/src/main/java/io/intrepid/contest/screens/contestoverview/ContestOverviewPresenter.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusActivity.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusContract.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenter.java
app/src/main/res/layout/activity_contest_overview.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/plurals.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/test/java/io/intrepid/contest/screens/contestoverview/ContestOverviewPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenterTest.java

https://intrepid.atlassian.net/browse/CON-140
- Added "todos" to hook up with Abass's recycler view and styles later
@abassawo can take over this subtask to display the scoring categories.
When you're done with that I can either take it back or you can do the remaining part (display the description and the score legend [1 poor, ..., 5 excellent], which you don't create adding a category, but I think comes from the server).

CON-140 Create contest overview screen

---

app/src/test/java/io/intrepid/contest/screens/splash/SplashPresenterTest.java

Small PR adding 1 test to `SplashPresenter` to make coverage 100%

Increase coverage in splash presenter

---

app/src/main/java/io/intrepid/contest/rest/ContestWrapper.java
app/src/main/java/io/intrepid/contest/rest/RestApi.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestPresenter.java

Removed mock code from presenter

Remove mock code from NewContestPresenter

---

app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestActivity.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/reviewcontest/ReviewContestContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/reviewcontest/ReviewContestFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/reviewcontest/ReviewContestPresenter.java
app/src/main/res/layout/fragment_review_contest.xml
app/src/main/res/layout/include_review_category_recycler_view.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/intrepid/contest/screens/contestcreation/reviewcontest/ReviewContestPresenterTest.java

Review Contest feature. Slightly updated to accommodate new architecture.

CON 39 - Review contest feature

---

app/src/main/res/layout/categories_list_fragment.xml

Small pr to fix the look and feel of the Categories List Fragment page.

Add padding to Fragment to match wireframes

---

app/src/main/java/io/intrepid/contest/models/Contact.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsActivity.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsAdapter.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsPresenter.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsViewHolder.java
app/src/main/res/drawable/close_icon.xml
app/src/main/res/drawable/search_icon.xml
app/src/main/res/layout/select_contacts_fragment.xml
app/src/main/res/values/styles.xml
app/src/test/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsPresenterTest.java

https://intrepid.atlassian.net/browse/CON-163
Like previous PR, this screen is not hooked up with the contest creation flow yet.
To test it in your phone/emulator, I recommend temporarily adding `startActivity(SendInvitationsActivity.makeIntent(this));` to the SplashActivity button click.
- Does not include selecting the contacts
Screens:
https://zpl.io/1gntQq
https://zpl.io/2sROmL

CON-163: Search contacts to invite contestants

---

app/src/main/java/io/intrepid/contest/models/Contact.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsActivity.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsAdapter.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsPresenter.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsViewHolder.java
app/src/main/res/drawable/selected_contact_icon.xml
app/src/main/res/layout/select_contacts_fragment.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsPresenterTest.java

https://intrepid.atlassian.net/browse/CON-164
Clicking on a contact should give visual feedback.
Design:
https://zpl.io/Z2kkNXr

CON-164: Select contacts UI

---

app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestActivity.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestMvpContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/reviewcontest/ReviewContestFragment.java

https://intrepid.atlassian.net/browse/CON-171
@abassawo Hopefully this doesn't interfere with code in your PRs; if you have a better idea on how to hook it up let me know.

CON-171: Navigate to Send Invitations screen after contest submission

---

app/src/main/java/io/intrepid/contest/models/Contest.java
app/src/main/java/io/intrepid/contest/rest/MockRestApi.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestPresenter.java

https://intrepid.atlassian.net/browse/CON-199
Tiny PR!
Without this I can't send the invitation through the API.

CON-199: Save contest id in persistent settings

---

app/src/main/java/io/intrepid/contest/screens/contestcreation/NonSwipingViewPager.java
app/src/main/res/layout/activity_viewpager_container.xml

ViewPager should not be controlled by swipe, but by
the appearing/disappearing buttons.

Con 198 - Introduce Custom No-Swipe ViewPager

---

app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsActivity.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsPresenter.java
app/src/main/res/layout/select_contacts_fragment.xml
app/src/test/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsPresenterTest.java

https://intrepid.atlassian.net/browse/CON-201

CON-201: improve search for contacts with minimum number of characters

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/intrepid/contest/models/Contact.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsActivity.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsActivityContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsPresenter.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/invitationintro/InvitationIntroContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/invitationintro/InvitationIntroFragment.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/invitationintro/InvitationIntroPresenter.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsAdapter.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsFragment.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsPresenter.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsViewHolder.java
app/src/main/res/layout/activity_send_invitations.xml
app/src/main/res/layout/fragment_invitation_intro.xml
app/src/main/res/layout/fragment_select_contacts.xml
app/src/main/res/layout/fragments_invite_contestants.xml
app/src/test/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/sendinvitations/invitationintro/InvitationIntroPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsPresenterTest.java

https://intrepid.atlassian.net/browse/CON-170
I'm sorry this is such a big PR! I needed to make a big refactor, and couldn't figure out a way to separate the changes.
- Does not include setting the back button actions (CON-197)
- Does not include api call

CON-170: Preview contacts that will be invited

---

app/src/main/java/io/intrepid/contest/rest/BatchInviteRequest.java
app/src/main/java/io/intrepid/contest/rest/BatchInviteResponse.java
app/src/main/java/io/intrepid/contest/rest/InvitationRequest.java
app/src/main/java/io/intrepid/contest/rest/InvitationResponse.java
app/src/main/java/io/intrepid/contest/rest/MockRestApi.java
app/src/main/java/io/intrepid/contest/rest/RestApi.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsPresenter.java
app/src/main/res/values/strings.xml
app/src/test/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/sendinvitations/invitationintro/InvitationRequestIntroPresenterTest.java

https://intrepid.atlassian.net/browse/CON-165

CON-165: Send invitations using the API

---

app/src/main/java/io/intrepid/contest/rest/InvitationRequest.java

https://intrepid.atlassian.net/browse/CON-207
Now API throws error when receiving empty phone/email

CON-207: Update API call to send email and phone only when not empty

---

app/src/main/java/io/intrepid/contest/ContestApplication.java
app/src/main/java/io/intrepid/contest/base/BaseActivity.java
app/src/main/java/io/intrepid/contest/base/BaseMvpActivity.java
app/src/main/java/io/intrepid/contest/settings/PersistentSettings.java
app/src/main/java/io/intrepid/contest/settings/SharedPreferencesManager.java
app/src/main/java/io/intrepid/contest/utils/ShakeDetector.java

* NOTE: Didn't unit test in the interest of expedience, esp since this is only meant for the demo

Clear preferences and reset Retrofit when we shake the device.

---

app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsPresenter.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/invitationintro/InvitationIntroContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/invitationintro/InvitationIntroFragment.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/invitationintro/InvitationIntroPresenter.java
app/src/main/res/layout/fragment_invitation_intro.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/sendinvitations/invitationintro/InvitationRequestIntroPresenterTest.java

https://intrepid.atlassian.net/browse/CON-202
This also raised the problem of hitting the back button after giving the app permissions, and I now restore the last screen that was being displayed.
https://zpl.io/1Ey6B7

CON-202: Add link to permissions screen

---

app/src/main/java/io/intrepid/contest/models/Contact.java
app/src/main/java/io/intrepid/contest/models/ParticipationType.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestPresenter.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsActivity.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsActivityContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsPresenter.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/invitationintro/InvitationIntroContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/invitationintro/InvitationIntroFragment.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/invitationintro/InvitationIntroPresenter.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsFragment.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsPresenter.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsViewHolder.java
app/src/main/res/layout/fragment_select_contacts.xml
app/src/main/res/values/plurals.xml
app/src/main/res/values/strings.xml
app/src/test/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/sendinvitations/invitationintro/InvitationRequestIntroPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsPresenterTest.java

https://intrepid.atlassian.net/browse/CON-14
Includes two subtasks:
- Create screen to invite judges
https://intrepid.atlassian.net/browse/CON-204
https://zpl.io/b1UVA
- Grey out contacts selected as contestants when selecting judges
https://intrepid.atlassian.net/browse/CON-205
https://zpl.io/Z2fE9N3

CON-14: Invite judges

---

app/src/main/java/io/intrepid/contest/base/BaseActivity.java

https://intrepid.atlassian.net/browse/CON-219

CON-219: Display toast messages only in dev debug

---

app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestoverview/ContestOverviewActivity.java
app/src/main/java/io/intrepid/contest/screens/contestoverview/ContestOverviewContract.java
app/src/main/java/io/intrepid/contest/screens/contestoverview/ContestOverviewPresenter.java
app/src/main/java/io/intrepid/contest/utils/SpannableUtil.java
app/src/main/res/layout/activity_contest_overview.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/plurals.xml
app/src/main/res/values/strings.xml

CON- 214  - Fix dynamic strings https://intrepid.atlassian.net/browse/CON-214
CON - 215 - Fix app bar title in Contest overview
COn - 216 - Remove toast after submitting

Remove large ugly toast after Contest is submitted

---

app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestActivity.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestMvpContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/describecontest/DescribeContestFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/namecontest/NameContestFragment.java
app/src/main/res/values/strings.xml

To-do: Add tests to NewContestPresenterTest after pr # 78 is merged in.

Fix titles for screens in Contest Creation Flow

---

app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestActivity.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsActivity.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsContract.java
app/src/main/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsPresenter.java

and disable backpress from splash screen back to Invitation screen

Enable backpress from Invitation screen

---

app/src/main/java/io/intrepid/contest/models/Category.java
app/src/main/java/io/intrepid/contest/models/Score.java

Fix bug sending the scores to the api

---

app/src/main/java/io/intrepid/contest/screens/contestcreation/NewContestPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/ValidatableContestCreationFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/ValidatableView.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListContract.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListFragment.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListPresenter.java
app/src/main/java/io/intrepid/contest/screens/contestcreation/namecontest/NameContestFragment.java
app/src/test/java/io/intrepid/contest/screens/contestcreation/NewContestPresenterTest.java
app/src/test/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListPresenterTest.java

Added tests to NewContestPresenterTest suite

Full coverage on New Contest Presenter Tests

---

app/src/main/java/io/intrepid/contest/customviews/ProgressIndicatorTextView.java
app/src/main/java/io/intrepid/contest/screens/adminstatus/AdminStatusActivity.java
app/src/main/res/layout/admin_status_activity.xml
app/src/main/res/layout/animatable_progress_text_view.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Use native progress bar to indicate a step in the Admin flow is "in progress"

Con229 -Refactor Admin Status page to show animated progress

---

app/src/main/java/io/intrepid/contest/customviews/HintLabelEditText.java
app/src/main/java/io/intrepid/contest/screens/join/JoinActivity.java
app/src/main/java/io/intrepid/contest/screens/join/JoinContract.java
app/src/main/java/io/intrepid/contest/screens/join/JoinPresenter.java
app/src/test/java/io/intrepid/contest/screens/join/JoinPresenterTest.java

As a contestant, if I copied the code from somewhere else (like a chat) I want to have the option to join a contest easily without pasting it manually
Some sample valid codes:
CKUeDdH
DguQXb5
7RVR9Dr

Con19 - Android - Pre-fill code from Clipboard

---

app/src/main/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListFragment.java

- Add conditional check to ensure the fragment has been added/attached before referencing the host activity.

Con230 - Fix crash in returning to Categories List Fragment

---

app/src/main/java/io/intrepid/contest/customviews/HintLabelEditText.java
app/src/main/res/layout/fragment_edit_contest_description.xml
app/src/main/res/layout/fragment_edit_contest_name.xml
app/src/main/res/values/attrs.xml

* Contest Name - capitalize every word
* Contest Description - capitalize first letter of every sentence.

Con209 - Accept Contest Name and Description in Sentence Case

---

app/src/main/java/io/intrepid/contest/customviews/HintLabelEditText.java
app/src/main/java/io/intrepid/contest/screens/join/JoinPresenter.java

- Prevent crash when navigating to Join Presenter page if clipboard data is null
- Change default InputType for HintLabelEditText to support expected keyboard behavior

Con-232 - Bug fixes on Join Presenter Page

---

app/src/main/java/io/intrepid/contest/models/ActiveContestListResponse.java
app/src/main/java/io/intrepid/contest/rest/MockRestApi.java
app/src/main/java/io/intrepid/contest/rest/RestApi.java
app/src/main/java/io/intrepid/contest/screens/splash/ContestAdapter.java
app/src/main/java/io/intrepid/contest/screens/splash/ContestRowViewHolder.java
app/src/main/java/io/intrepid/contest/screens/splash/SplashActivity.java
app/src/main/java/io/intrepid/contest/screens/splash/SplashContract.java
app/src/main/java/io/intrepid/contest/screens/splash/SplashPresenter.java
app/src/main/res/layout/activity_splash.xml
app/src/main/res/layout/contest_row_item.xml
app/src/main/res/values/dimens.xml
app/src/test/java/io/intrepid/contest/screens/splash/SplashPresenterTest.java

Displays recycler view of ongoing contests.
- No action on click as of yet, and some light refactoring of SplashPresenterTest along with new test cases.

Con 95 - Initial Commit - Rejoin Contest

---

app/src/main/java/io/intrepid/contest/rest/RestApi.java

Changed route api. It has also been updated in the contest server wiki.

Fix close submissions api route

---

app/src/main/java/io/intrepid/contest/rest/MockRestApi.java
app/src/main/java/io/intrepid/contest/rest/RestApi.java
app/src/main/java/io/intrepid/contest/screens/splash/SplashPresenter.java
app/src/test/java/io/intrepid/contest/screens/splash/SplashPresenterTest.java

https://intrepid.atlassian.net/browse/CON-238
API call doesn't take user ID in the endpoint

CON-238: Fix API call to get previous contests

---

app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusActivity.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusContract.java
app/src/main/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenter.java
app/src/test/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenterTest.java

https://intrepid.atlassian.net/browse/CON-240

CON-240: Go back to splash screen from contest status screen

---

README.md

https://intrepid.atlassian.net/browse/CON-241

CON-241: Add Readme

---

app/src/test/java/io/intrepid/contest/screens/contestcreation/categorieslist/CategoriesListPresenterTest.kt
app/src/test/java/io/intrepid/contest/screens/contestjudging/scoreentries/ScoreEntriesPresenterTest.kt
app/src/test/java/io/intrepid/contest/screens/contestjudging/scoreentries/entrydetail/EntryDetailPresenterTest.kt
app/src/test/java/io/intrepid/contest/screens/contestresults/ContestResultsPresenterTest.kt
app/src/test/java/io/intrepid/contest/screens/conteststatus/ContestStatusPresenterTest.kt
app/src/test/java/io/intrepid/contest/screens/entrysubmission/entryimage/EntryImagePresenterTest.kt
app/src/test/java/io/intrepid/contest/screens/join/JoinPresenterTest.kt
app/src/test/java/io/intrepid/contest/screens/sendinvitations/SendInvitationsPresenterTest.kt
app/src/test/java/io/intrepid/contest/screens/sendinvitations/invitationintro/InvitationRequestIntroPresenterTest.kt
app/src/test/java/io/intrepid/contest/screens/sendinvitations/selectcontacts/SelectContactsPresenterTest.kt
app/src/test/java/io/intrepid/contest/screens/splash/SplashPresenterTest.kt

Used group object initialization to make the code a little more "kotlin-style"

Use group object initialization
